version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: teosvain/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    container_name: foodgram-front
    image: teosvain/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/app/media
      - static:/static